# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mycel < Formula
  desc "Orchestration for AI agents"
  homepage "https://bc-infra.com"
  version "0.2.5"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel?
    if Hardware::CPU.is_64_bit?
      url "https://github.com/rpuneet/mycel/releases/download/v0.2.5/mycel_0.2.5_linux_amd64.tar.gz"
      sha256 "6df849e8113627c9de5702cc6edc03578d5f19cd65fc20ae44597e577e582fa7"

      def install
        bin.install "mycel"
      end
    end
  end
  if Hardware::CPU.arm?
    if Hardware::CPU.is_64_bit?
      url "https://github.com/rpuneet/mycel/releases/download/v0.2.5/mycel_0.2.5_linux_arm64.tar.gz"
      sha256 "5aa67242a63a5f3256391efc8237cc969446b45ba93218ecaf2f78712f658e40"

      def install
        bin.install "mycel"
      end
    end
  end

  test do
    system "#{bin}/mycel", "version"
  end
end
